server:
  port: 8008
spring:
  application:
    name: productions-provider
  cloud:
    nacos:
      discovery:
        server-addr: 121.43.145.142:8849,121.43.145.142:8851 #nacos服务的地址 不要加http
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xhh.ddos-sec.cn:3306/erp?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 1234
mybatis: #配置mybatis sql打印
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:cn/ddosec/production/mapper/*.xml
  type-aliases-package: cn.ddosec.domain.pojo
